name: Build MediaProcessor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg cmake nlohmann-json3-dev libsndfile1-dev

      - name: Compile MediaProcessor
        run: |
          cd MediaProcessor
          mkdir -p build
          cd build
          cmake ..
          make
